### ISSUE TITLE
css sourcemap hinders liveCss reload

### ISSUE THREAD

**Issue by thomasmattheussen** [EHLOVader/laravel-elixir-livereload#10]
When using sass + sourcemaps, the liveCss option doesn't work, because it tries to reload the sourcemap. So everytime file.css is created, file.css.map is also created and then it does a hard refresh.

My temporary fix is to exclude the sourcemap file in the src option for livereload.

**Comment by EHLOVader** [comment]
This is more than just a refresh problem. Were you (or I) to bypass the full page reload your map would not match anymore. 

Looking into a way to livereload maps, and avoid these issues. Open to any ideas if you had them. 

After looking into it I have yet to find a way to pull this off. Everything I have found suggests that sourcemaps have plagued the livereload project for years. So refreshing is likely the best way to handle this. Will add `'!**/*.map'` to the default src pattern.
