### ISSUE TITLE
browser reload doesn't seem to work

### ISSUE THREAD

**Issue by ammonkc** [EHLOVader/laravel-elixir-livereload#17]
the package doesn't seem to be working at all for me. when I change a file the console says file "reloaded" but the browser never refreshes. I have the livereload browser extension enabled, and have also tried manually adding the js snippet to the html. Am I missing a step? 

I'm running Laravel 5.2, laravel-elixir 5.0, and laravel-elixir-livereload 1.1.5

**Comment by EHLOVader** [comment]
What does your gulpfile look like?

Is it related to the CSS live loading? If it is just a CSS change it
shouldn't reload, the changes should just happen.

**Comment by EHLOVader** [comment]
OH it is related to the fixes applied for #16.

Pin your dependencies to 1.1.4 instead. 
The only change in 1.1.5 was bumping dep to v5.0 on elixir. Although a new version of elixir was released, it hasn't been released in the Laravel package.

I will work on a solution for that.
