### ISSUE TITLE
Any chance of supporting elixir 5.0?

### ISSUE THREAD

**Issue by aygee** [EHLOVader/laravel-elixir-livereload#18]
I'm running the elixir livereload 1.1.4 with elixir 5.0 and its running smoothly.

**Comment by aygee** [comment]
Nvm, there is already a commit to bump up the dependency.

**Comment by EHLOVader** [comment]
Yup... You can read more on it here. https://github.com/EHLOVader/laravel-elixir-livereload/pull/16#issuecomment-186971209

The laravel/laravel project doesn't use elixir 5 so I cannot up the dependency without causing some problems. Perhaps I can ditch the peerDependencies but they were necessary when the Elixir api changed drastically a few versions back.
