### ISSUE TITLE
pass options to gulp.watch()

### ISSUE THREAD

**Issue by denis-chmel** [EHLOVader/laravel-elixir-livereload#19]
Hello @EHLOVader,
There's an annoying gulp.watch issue on MacOs/Ubuntu (at least). The CPU load goes crazy and eats battery too fast. Unless you set "{ interval: 500 }" as a 2nd param to gulp.watch, issue is here:
https://github.com/gulpjs/gulp/issues/634

Do you think it is reasonable to allow passing params to gulp watch? e.g.

``` javascript
var options = {
  // ... 
  gulpWatch: {
     interval: 1000
  }
}
mix.livereload(src, options);
```

What do you think?

**Comment by denis-chmel** [comment]
You know what, forget about it.
The gulp.watch is also used inside mix.sass() and who knows where, so it makes more sense to make gulp.watch support global params somehow.

**Comment by EHLOVader** [comment]
I would be interested in following this. Do you plan on opening an issue or similar with [laravel-elixir](https://github.com/laravel/elixir) to provide an API for such things centrally?

**Comment by denis-chmel** [comment]
Good idea. Raised it here:
https://github.com/laravel/elixir/issues/467
