### ISSUE TITLE
How can another computer still work?

### ISSUE THREAD

**Issue by frankyxhl** [EHLOVader/laravel-elixir-livereload#3]
Nice project,Thanks!

I have a question.I also want to use this livereload function on another device like iPad.So I change the javascript code "//localhost:35729/livereload.js?snipver=1" to my dev computer IP address "//192.168.1.185:35729/livereload.js?snipver=1".But not work.

I guess I should give some options like {host:"129.168.1.185"} for laravel-elixir-livereload ,right?But I don't know how to do.

Thanks.

**Comment by EHLOVader** [comment]
Ooh, interesting idea. 

I hadn't thought of that use case but I can see if it could be easily integrated.

**Comment by EHLOVader** [comment]
@frankyxhl you should be able to pass through any options from the second parameter of the `livereload` call. `null` should work if you wish to use the default `src` globs still.

Hopefully this helps in configuring livereload for external devices. If not, you may wish to look into [browsersync](https://github.com/anheru88/laravel-elixir-browser-sync)

**Comment by EHLOVader** [comment]
I reread your issue though.

Found [this](http://feedback.livereload.com/knowledgebase/articles/86232-how-do-i-use-livereload-on-iphone-ipad-android-etc) 

It looks like you don't need to do any configuration. You just need a good way to handle adding livereload script to your application. 
With the correct IP.

**Comment by frankyxhl** [comment]
Thanks.I will have a try~
