### ISSUE TITLE
Enable liveCSS by default

### ISSUE THREAD

**Issue by jadjoubran** [EHLOVader/laravel-elixir-livereload#9]
```
mix.livereload([
            'public/js/vendor.js',
            'public/js/app.js',
            'public/css/vendor.css',
            'public/css/app.css',
            'public/views/**/*.html'
        ], {liveCSS: true});
```

enabling liveCSS would soft reload the page when CSS changes (injects the new css) instead of a full page reload..

If you think it's a good idea to enable it by default, I can submit a PR.
Else, this would be useful for someone looking for liveCSS.

**Comment by EHLOVader** [comment]
That is how livereload works by default.

Where do you see that that liveCSS is an option for livereload?

https://www.npmjs.com/package/gulp-livereload

**Comment by jadjoubran** [comment]
There you go https://github.com/vohof/gulp-livereload/pull/58
This pull request shows that it's enabled by default.. but I don't think it's the case here

It's not a bug, it's just a feature suggestion

**Comment by EHLOVader** [comment]
Yeah. The adding pass through of options is planned. Because of #3
actually.

I see now how the options are passed through on gulp-livereload to the
server. Should add those in the readme also as part of #6

Thanks

**Comment by jadjoubran** [comment]
hmm I'm not sure if you got my idea.. This is alreayd working if you use the code that I showed you.. I'm using it here https://github.com/jadjoubran/laravel5-angular-material-starter/blob/master/gulpfile.js

I was just suggesting enabling it by default

**Comment by EHLOVader** [comment]
I understood what you meant, but I wasn't able to explain myself clearly either. The pass through for options is a simple one.

The most recent version should allow that, if you were for some reason on the master/v3.x branch it would have already passed the options through to the server on listen. 

The option for liveCSS is already a [default to true.](https://github.com/mklabs/tiny-lr/#options) so I don't know how this will change things, but hopefully it does.
